### ISSUE TITLE
DHCP implementation

### ISSUE THREAD

**Issue by bictorv** [dseagrav/Lambda-system-software#1]
There is no support for DHCP in the original system, so I wrote an implementation. See https://www.aosnet.ch/lispm-dhcp for more info and a tape archive.

**Comment by dseagrav** [comment]
Björn's stuff has moved to chaosnet.net, so this is now at https://chaosnet.net/lispm-dhcp

**Comment by dseagrav** [comment]
I'm going to close this issue, as the issues here are obsolete in the bogodyne releases.
