### ISSUE TITLE
DNS resolver implementation

### ISSUE THREAD

**Issue by bictorv** [dseagrav/Lambda-system-software#2]
There is no support for DNS in the original system, so I ported my old implementation for TI Explorers to the Lambda. See https://www.aosnet.ch/lispm-dns for more info and a tape archive.

**Comment by noahfriedman** [comment]
URL is currently 404

**Comment by dseagrav** [comment]
Björn's stuff has moved to chaosnet.net - Try https://chaosnet.net/lispm-dns

**Comment by dseagrav** [comment]
I'm going to close this issue, as the issues here are obsolete in the bogodyne releases.
